In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("card_transdata.csv")

In [5]:
df.head(3)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0

In [6]:
y=df["fraud"]
x=df.drop("fraud",axis=1)
len(df)

1000000

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.9)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
lr=LogisticRegression()

In [10]:
model=lr.fit(x_train,y_train)
model.score(x_test,y_test)

c:\Users\Merve\Desktop\PythonProjects\python-for-ai\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.95878

In [11]:
df["fraud"].value_counts()

fraud
0.0    912597
1.0     87403
Name: count, dtype: int64

In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
y_pred=model.predict(x_test)

In [22]:
confusion_matrix(y_test,y_pred)

array([[90661,   636],
       [ 3486,  5217]])

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
tree=DecisionTreeClassifier()

In [21]:
model_tree=tree.fit(x_train,y_train)
model_tree.score(x_test,y_test)

1.0

In [18]:
y_tree_pred=model_tree.predict(x_test)

In [23]:
confusion_matrix(y_test,y_tree_pred)

array([[91297,     0],
       [    0,  8703]])

In [24]:
a=pd.DataFrame()
a["true"]=y_test
a["pred"]=y_pred

In [25]:
a

        true  pred
987231   0.0   0.0
79954    0.0   0.0
567130   0.0   0.0
500891   0.0   0.0
55399    0.0   0.0
...      ...   ...
395942   0.0   0.0
417771   0.0   0.0
937140   0.0   0.0
794022   0.0   0.0
573083   0.0   0.0

[100000 rows x 2 columns]

In [27]:
a[a["true"]==1].value_counts()

true  pred
1.0   1.0     5217
      0.0     3486
Name: count, dtype: int64